### ISSUE TITLE
Font support

### ISSUE THREAD

**Issue by matthewwyndham** [Jtschwantes/Prysm#11]
Is it possible to set up Prysm so that it can control fonts and font-sizes too? That would be dope.

**Comment by Jtschwantes** [comment]
I'll look into it, thanks for the suggestion. 

The escape characters that the library uses to change the colors also have some settings for fonts, so it might be possible to use those. There are some escape characters that don't work in most command prompts and I'm curious to see if fonts are included in those or not.

**Comment by Jtschwantes** [comment]
So it looks like it's definitely possible. I feel it's out of the scope of this package because it's a more complex solution and I'm intending for the package to remain as lightweight as possible. I'll make a more heavy version soon, when I have this package in a ready state.

Thanks for the suggestion!
